In [4]:
import sympy as sp
import pandas as pd
import numpy as np
import scipy.linalg as sp1
import math

In [85]:
def getp1(x,beta):
    p1 = math.exp(beta.dot(x.transpose()))/(1+math.exp(beta.dot(x.transpose())))
    return p1
def logistic_regression(label_class, df):
    x = np.array(df)
    x = np.column_stack((x,np.ones(len(x),dtype = int)))
    beta = (np.random.randn(len(x[0]), 1) * 0.0000005 + 1).transpose()
    print(beta)
    print(beta)
    for i in range(100):
        first_deriv = -1*x[0]*(label[0]-getp1(x[0],beta))
        second_deriv = float(x[0]@x[0].transpose()*getp1(x[0],beta)*(1-getp1(x[0],beta)))
        for l in range(1,len(x)):
            first_deriv -= x[l]*(label[l]-getp1(x[l],beta))
            second_deriv += float(np.dot(x[l],x[l].transpose())*getp1(x[l],beta)*(1-getp1(x[l],beta)))
        if second_deriv == 0.00000:
            print("stopped on the {}th run".format(i))
            break
        beta = beta - (first_deriv/second_deriv)
    print(beta)
    print(math.exp(beta.dot(np.array([10,1,1]).transpose()))/(1+math.exp(beta.dot(np.array([10,1,1]).transpose()))))
test = pd.read_csv("test.csv")
print(test)
label = test["label"]
test = test.drop(columns=["label"])
logistic_regression(label,test)

    Value  label    value1
0     0.0      0  0.700000
1     0.1      0  0.600000
2     0.2      0  0.500000
3     0.3      0  0.400000
4     0.4      0  0.300000
5     0.5      0  0.200000
6     0.6      1  0.100000
7     0.7      1  0.001000
8     0.8      1  0.000100
9     0.9      1  0.000001
10    1.0      1  0.000000
[[1.00000101 1.00000049 1.00000035]]
[[1.00000101 1.00000049 1.00000035]]
[[ 10.74958672 -10.60857867  -4.26062738]]
1.0
